# Generated by Django 5.1.7 on 2025-05-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('rider', 'Rider'), ('admin', 'Admin')], max_length=10),
        ),
    ]
