# Generated by Django 5.1.7 on 2025-05-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('rider', 'Rider'), ('admin', 'Admin'), ('demo', 'Demo')], max_length=10),
        ),
    ]
