# Generated by Django 5.1.7 on 2025-05-08 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_riderearnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderearnings',
            name='earned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
