# Generated by Django 5.1.7 on 2025-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_riderearnings_earned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderearnings',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
