# Generated by Django 5.2.5 on 2025-10-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_alter_riderearnings_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
