# Generated by Django 5.1.7 on 2025-10-19 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_alter_rider_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your profile picture', max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
