# Generated by Django 5.1.7 on 2025-05-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_token_number'),
    ]

    operations = [
    ]
