# Generated by Django 5.1.7 on 2025-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='baranggay',
            field=models.CharField(default='Marawi', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_profiles/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(default='Restaurant', max_length=100),
        ),
    ]
