# Generated by Django 5.1.7 on 2025-05-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_baranggay_restaurant_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='baranggay',
            new_name='barangay',
        ),
    ]
