# Generated by Django 5.1.7 on 2025-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_baranggay_restaurant_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='X7Q3+FF Marawi City, Lanao del Sur, Philippines', max_length=100),
        ),
    ]
