# Generated by Django 5.2.5 on 2025-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='restaurant_profiles/'),
        ),
    ]
