# Generated by Django 5.1.7 on 2025-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_products/'),
        ),
    ]
