# Generated by Django 5.1.7 on 2025-04-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cartitem'),
        ('restaurant', '0002_restaurant_baranggay_restaurant_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
