# Generated by Django 5.2.5 on 2025-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_cartitem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='restaurant_products/'),
        ),
    ]
