# Generated by Django 5.1.7 on 2025-05-01 15:09

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.CharField(blank=True, default=orders.models.generate_unique_token, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('assigned', 'Assigned'), ('ready', 'Ready'), ('otw', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
