# Generated by Django 5.1.7 on 2025-05-01 15:11

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_token_number_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_number',
            field=models.CharField(default=orders.models.generate_unique_token, max_length=6, unique=True),
        ),
    ]
