# Generated by Django 5.1.7 on 2025-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
