# Generated by Django 5.1.7 on 2025-05-09 14:43

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20250509_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_number',
            field=models.CharField(default=orders.models.generate_unique_token, max_length=10, unique=True),
        ),
    ]
