# Generated by Django 5.1.7 on 2025-05-09 14:44

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_number',
            field=models.CharField(default=orders.models.generate_unique_token, max_length=8, unique=True),
        ),
    ]
