# Generated by Django 5.1.7 on 2025-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_of_delivery_url',
            field=models.URLField(blank=True, help_text='AWS S3 URL for proof of delivery image/file', max_length=500, null=True),
        ),
    ]
