# Generated by Django 5.2.5 on 2025-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_stripe_fields'),
        ('orders', '0009_order_proof_of_delivery_url'),
    ]

    operations = [
    ]
